/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as CruisesIndexRouteImport } from './routes/cruises.index'
import { Route as CruisesSlugRouteImport } from './routes/cruises.$slug'
import { Route as ExcursionsSlugRouteImport } from './routes/excursions.$slug'
import { Route as PortsSlugRouteImport } from './routes/ports.$slug'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedBookingSlugRouteImport } from './routes/_authenticated/booking.$slug'
import { Route as AuthenticatedBookingReturnRouteImport } from './routes/_authenticated/booking.return'
import { Route as AuthenticatedAccountBookingsIndexRouteImport } from './routes/_authenticated/account.bookings.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CruisesIndexRoute = CruisesIndexRouteImport.update({
  id: '/cruises/',
  path: '/cruises/',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesSlugRoute = CruisesSlugRouteImport.update({
  id: '/cruises/$slug',
  path: '/cruises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionsSlugRoute = ExcursionsSlugRouteImport.update({
  id: '/excursions/$slug',
  path: '/excursions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsSlugRoute = PortsSlugRouteImport.update({
  id: '/ports/$slug',
  path: '/ports/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/admin/audit-log',
    path: '/admin/audit-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingSlugRoute =
  AuthenticatedBookingSlugRouteImport.update({
    id: '/booking/$slug',
    path: '/booking/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingReturnRoute =
  AuthenticatedBookingReturnRouteImport.update({
    id: '/booking/return',
    path: '/booking/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountBookingsIndexRoute =
  AuthenticatedAccountBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/cruises/$slug': typeof CruisesSlugRoute
  '/excursions/$slug': typeof ExcursionsSlugRoute
  '/ports/$slug': typeof PortsSlugRoute
  '/cruises/': typeof CruisesIndexRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/booking/$slug': typeof AuthenticatedBookingSlugRoute
  '/booking/return': typeof AuthenticatedBookingReturnRoute
  '/account/bookings/': typeof AuthenticatedAccountBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/cruises/$slug': typeof CruisesSlugRoute
  '/excursions/$slug': typeof ExcursionsSlugRoute
  '/ports/$slug': typeof PortsSlugRoute
  '/cruises': typeof CruisesIndexRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/booking/$slug': typeof AuthenticatedBookingSlugRoute
  '/booking/return': typeof AuthenticatedBookingReturnRoute
  '/account/bookings': typeof AuthenticatedAccountBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/cruises/$slug': typeof CruisesSlugRoute
  '/excursions/$slug': typeof ExcursionsSlugRoute
  '/ports/$slug': typeof PortsSlugRoute
  '/cruises/': typeof CruisesIndexRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/booking/$slug': typeof AuthenticatedBookingSlugRoute
  '/_authenticated/booking/return': typeof AuthenticatedBookingReturnRoute
  '/_authenticated/account/bookings/': typeof AuthenticatedAccountBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/account'
    | '/cruises/$slug'
    | '/excursions/$slug'
    | '/ports/$slug'
    | '/cruises/'
    | '/admin/audit-log'
    | '/booking/$slug'
    | '/booking/return'
    | '/account/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/account'
    | '/cruises/$slug'
    | '/excursions/$slug'
    | '/ports/$slug'
    | '/cruises'
    | '/admin/audit-log'
    | '/booking/$slug'
    | '/booking/return'
    | '/account/bookings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/_authenticated/account'
    | '/cruises/$slug'
    | '/excursions/$slug'
    | '/ports/$slug'
    | '/cruises/'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/booking/$slug'
    | '/_authenticated/booking/return'
    | '/_authenticated/account/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CruisesSlugRoute: typeof CruisesSlugRoute
  ExcursionsSlugRoute: typeof ExcursionsSlugRoute
  PortsSlugRoute: typeof PortsSlugRoute
  CruisesIndexRoute: typeof CruisesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cruises/': {
      id: '/cruises/'
      path: '/cruises'
      fullPath: '/cruises/'
      preLoaderRoute: typeof CruisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises/$slug': {
      id: '/cruises/$slug'
      path: '/cruises/$slug'
      fullPath: '/cruises/$slug'
      preLoaderRoute: typeof CruisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excursions/$slug': {
      id: '/excursions/$slug'
      path: '/excursions/$slug'
      fullPath: '/excursions/$slug'
      preLoaderRoute: typeof ExcursionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports/$slug': {
      id: '/ports/$slug'
      path: '/ports/$slug'
      fullPath: '/ports/$slug'
      preLoaderRoute: typeof PortsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking/$slug': {
      id: '/_authenticated/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/booking/$slug'
      preLoaderRoute: typeof AuthenticatedBookingSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking/return': {
      id: '/_authenticated/booking/return'
      path: '/booking/return'
      fullPath: '/booking/return'
      preLoaderRoute: typeof AuthenticatedBookingReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/bookings/': {
      id: '/_authenticated/account/bookings/'
      path: '/bookings'
      fullPath: '/account/bookings/'
      preLoaderRoute: typeof AuthenticatedAccountBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountBookingsIndexRoute: typeof AuthenticatedAccountBookingsIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountBookingsIndexRoute:
    AuthenticatedAccountBookingsIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedBookingSlugRoute: typeof AuthenticatedBookingSlugRoute
  AuthenticatedBookingReturnRoute: typeof AuthenticatedBookingReturnRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedBookingSlugRoute: AuthenticatedBookingSlugRoute,
  AuthenticatedBookingReturnRoute: AuthenticatedBookingReturnRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CruisesSlugRoute: CruisesSlugRoute,
  ExcursionsSlugRoute: ExcursionsSlugRoute,
  PortsSlugRoute: PortsSlugRoute,
  CruisesIndexRoute: CruisesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
