/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthResetRouteImport } from './routes/auth_.reset'
import { Route as CruisesIndexRouteImport } from './routes/cruises.index'
import { Route as CruisesSlugRouteImport } from './routes/cruises.$slug'
import { Route as ExcursionsSlugRouteImport } from './routes/excursions.$slug'
import { Route as PortsSlugRouteImport } from './routes/ports.$slug'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account.profile'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin/bookings'
import { Route as AuthenticatedAdminExcursionsRouteImport } from './routes/_authenticated/admin/excursions'
import { Route as AuthenticatedAdminPortsRouteImport } from './routes/_authenticated/admin/ports'
import { Route as AuthenticatedAdminRefundsRouteImport } from './routes/_authenticated/admin/refunds'
import { Route as AuthenticatedAdminSailingsRouteImport } from './routes/_authenticated/admin/sailings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedBookingSlugRouteImport } from './routes/_authenticated/booking.$slug'
import { Route as AuthenticatedBookingReturnRouteImport } from './routes/_authenticated/booking.return'
import { Route as AuthenticatedAccountBookingsIndexRouteImport } from './routes/_authenticated/account.bookings.index'
import { Route as AuthenticatedAccountBookingsReferenceRouteImport } from './routes/_authenticated/account.bookings.$reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/auth_/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesIndexRoute = CruisesIndexRouteImport.update({
  id: '/cruises/',
  path: '/cruises/',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesSlugRoute = CruisesSlugRouteImport.update({
  id: '/cruises/$slug',
  path: '/cruises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcursionsSlugRoute = ExcursionsSlugRouteImport.update({
  id: '/excursions/$slug',
  path: '/excursions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsSlugRoute = PortsSlugRouteImport.update({
  id: '/ports/$slug',
  path: '/ports/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExcursionsRoute =
  AuthenticatedAdminExcursionsRouteImport.update({
    id: '/excursions',
    path: '/excursions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPortsRoute = AuthenticatedAdminPortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminRefundsRoute =
  AuthenticatedAdminRefundsRouteImport.update({
    id: '/refunds',
    path: '/refunds',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSailingsRoute =
  AuthenticatedAdminSailingsRouteImport.update({
    id: '/sailings',
    path: '/sailings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedBookingSlugRoute =
  AuthenticatedBookingSlugRouteImport.update({
    id: '/booking/$slug',
    path: '/booking/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingReturnRoute =
  AuthenticatedBookingReturnRouteImport.update({
    id: '/booking/return',
    path: '/booking/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountBookingsIndexRoute =
  AuthenticatedAccountBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountBookingsReferenceRoute =
  AuthenticatedAccountBookingsReferenceRouteImport.update({
    id: '/bookings/$reference',
    path: '/bookings/$reference',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/auth/reset': typeof AuthResetRoute
  '/cruises/$slug': typeof CruisesSlugRoute
  '/excursions/$slug': typeof ExcursionsSlugRoute
  '/ports/$slug': typeof PortsSlugRoute
  '/cruises/': typeof CruisesIndexRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/excursions': typeof AuthenticatedAdminExcursionsRoute
  '/admin/ports': typeof AuthenticatedAdminPortsRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/sailings': typeof AuthenticatedAdminSailingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/booking/$slug': typeof AuthenticatedBookingSlugRoute
  '/booking/return': typeof AuthenticatedBookingReturnRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/account/bookings/$reference': typeof AuthenticatedAccountBookingsReferenceRoute
  '/account/bookings/': typeof AuthenticatedAccountBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/auth/reset': typeof AuthResetRoute
  '/cruises/$slug': typeof CruisesSlugRoute
  '/excursions/$slug': typeof ExcursionsSlugRoute
  '/ports/$slug': typeof PortsSlugRoute
  '/cruises': typeof CruisesIndexRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/excursions': typeof AuthenticatedAdminExcursionsRoute
  '/admin/ports': typeof AuthenticatedAdminPortsRoute
  '/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/admin/sailings': typeof AuthenticatedAdminSailingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/booking/$slug': typeof AuthenticatedBookingSlugRoute
  '/booking/return': typeof AuthenticatedBookingReturnRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/account/bookings/$reference': typeof AuthenticatedAccountBookingsReferenceRoute
  '/account/bookings': typeof AuthenticatedAccountBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/auth_/reset': typeof AuthResetRoute
  '/cruises/$slug': typeof CruisesSlugRoute
  '/excursions/$slug': typeof ExcursionsSlugRoute
  '/ports/$slug': typeof PortsSlugRoute
  '/cruises/': typeof CruisesIndexRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/excursions': typeof AuthenticatedAdminExcursionsRoute
  '/_authenticated/admin/ports': typeof AuthenticatedAdminPortsRoute
  '/_authenticated/admin/refunds': typeof AuthenticatedAdminRefundsRoute
  '/_authenticated/admin/sailings': typeof AuthenticatedAdminSailingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/booking/$slug': typeof AuthenticatedBookingSlugRoute
  '/_authenticated/booking/return': typeof AuthenticatedBookingReturnRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/account/bookings/$reference': typeof AuthenticatedAccountBookingsReferenceRoute
  '/_authenticated/account/bookings/': typeof AuthenticatedAccountBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/admin'
    | '/account'
    | '/auth/reset'
    | '/cruises/$slug'
    | '/excursions/$slug'
    | '/ports/$slug'
    | '/cruises/'
    | '/account/profile'
    | '/admin/audit-log'
    | '/admin/bookings'
    | '/admin/excursions'
    | '/admin/ports'
    | '/admin/refunds'
    | '/admin/sailings'
    | '/admin/users'
    | '/booking/$slug'
    | '/booking/return'
    | '/account/'
    | '/admin/'
    | '/account/bookings/$reference'
    | '/account/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/auth/reset'
    | '/cruises/$slug'
    | '/excursions/$slug'
    | '/ports/$slug'
    | '/cruises'
    | '/account/profile'
    | '/admin/audit-log'
    | '/admin/bookings'
    | '/admin/excursions'
    | '/admin/ports'
    | '/admin/refunds'
    | '/admin/sailings'
    | '/admin/users'
    | '/booking/$slug'
    | '/booking/return'
    | '/account'
    | '/admin'
    | '/account/bookings/$reference'
    | '/account/bookings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/_authenticated/admin'
    | '/_authenticated/account'
    | '/auth_/reset'
    | '/cruises/$slug'
    | '/excursions/$slug'
    | '/ports/$slug'
    | '/cruises/'
    | '/_authenticated/account/profile'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/excursions'
    | '/_authenticated/admin/ports'
    | '/_authenticated/admin/refunds'
    | '/_authenticated/admin/sailings'
    | '/_authenticated/admin/users'
    | '/_authenticated/booking/$slug'
    | '/_authenticated/booking/return'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/account/bookings/$reference'
    | '/_authenticated/account/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  AuthResetRoute: typeof AuthResetRoute
  CruisesSlugRoute: typeof CruisesSlugRoute
  ExcursionsSlugRoute: typeof ExcursionsSlugRoute
  PortsSlugRoute: typeof PortsSlugRoute
  CruisesIndexRoute: typeof CruisesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/reset': {
      id: '/auth_/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises/': {
      id: '/cruises/'
      path: '/cruises'
      fullPath: '/cruises/'
      preLoaderRoute: typeof CruisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises/$slug': {
      id: '/cruises/$slug'
      path: '/cruises/$slug'
      fullPath: '/cruises/$slug'
      preLoaderRoute: typeof CruisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excursions/$slug': {
      id: '/excursions/$slug'
      path: '/excursions/$slug'
      fullPath: '/excursions/$slug'
      preLoaderRoute: typeof ExcursionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports/$slug': {
      id: '/ports/$slug'
      path: '/ports/$slug'
      fullPath: '/ports/$slug'
      preLoaderRoute: typeof PortsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/excursions': {
      id: '/_authenticated/admin/excursions'
      path: '/excursions'
      fullPath: '/admin/excursions'
      preLoaderRoute: typeof AuthenticatedAdminExcursionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ports': {
      id: '/_authenticated/admin/ports'
      path: '/ports'
      fullPath: '/admin/ports'
      preLoaderRoute: typeof AuthenticatedAdminPortsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/refunds': {
      id: '/_authenticated/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AuthenticatedAdminRefundsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/sailings': {
      id: '/_authenticated/admin/sailings'
      path: '/sailings'
      fullPath: '/admin/sailings'
      preLoaderRoute: typeof AuthenticatedAdminSailingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/booking/$slug': {
      id: '/_authenticated/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/booking/$slug'
      preLoaderRoute: typeof AuthenticatedBookingSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking/return': {
      id: '/_authenticated/booking/return'
      path: '/booking/return'
      fullPath: '/booking/return'
      preLoaderRoute: typeof AuthenticatedBookingReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/bookings/': {
      id: '/_authenticated/account/bookings/'
      path: '/bookings'
      fullPath: '/account/bookings/'
      preLoaderRoute: typeof AuthenticatedAccountBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/bookings/$reference': {
      id: '/_authenticated/account/bookings/$reference'
      path: '/bookings/$reference'
      fullPath: '/account/bookings/$reference'
      preLoaderRoute: typeof AuthenticatedAccountBookingsReferenceRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminExcursionsRoute: typeof AuthenticatedAdminExcursionsRoute
  AuthenticatedAdminPortsRoute: typeof AuthenticatedAdminPortsRoute
  AuthenticatedAdminRefundsRoute: typeof AuthenticatedAdminRefundsRoute
  AuthenticatedAdminSailingsRoute: typeof AuthenticatedAdminSailingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
    AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
    AuthenticatedAdminExcursionsRoute: AuthenticatedAdminExcursionsRoute,
    AuthenticatedAdminPortsRoute: AuthenticatedAdminPortsRoute,
    AuthenticatedAdminRefundsRoute: AuthenticatedAdminRefundsRoute,
    AuthenticatedAdminSailingsRoute: AuthenticatedAdminSailingsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAccountBookingsReferenceRoute: typeof AuthenticatedAccountBookingsReferenceRoute
  AuthenticatedAccountBookingsIndexRoute: typeof AuthenticatedAccountBookingsIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAccountBookingsReferenceRoute:
    AuthenticatedAccountBookingsReferenceRoute,
  AuthenticatedAccountBookingsIndexRoute:
    AuthenticatedAccountBookingsIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedBookingSlugRoute: typeof AuthenticatedBookingSlugRoute
  AuthenticatedBookingReturnRoute: typeof AuthenticatedBookingReturnRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedBookingSlugRoute: AuthenticatedBookingSlugRoute,
  AuthenticatedBookingReturnRoute: AuthenticatedBookingReturnRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  AuthResetRoute: AuthResetRoute,
  CruisesSlugRoute: CruisesSlugRoute,
  ExcursionsSlugRoute: ExcursionsSlugRoute,
  PortsSlugRoute: PortsSlugRoute,
  CruisesIndexRoute: CruisesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
